
-- Conexão 1 - SCAN
DECLARE @i int = 1
DECLARE @Result int
DECLARE @Result_MiddleName nvarchar(50)
WHILE @i > 0 BEGIN
SELECT @Result = count(*) FROM AdventureWorks.Person.Person
WAITFOR DELAY '00:00:00.002'
end
go

-- Conexão 2 - Seek
DECLARE @i int = 1
DECLARE @Result int
DECLARE @Result_MiddleName nvarchar(50)
WHILE @i > 0 BEGIN
--SELECT @Result = count(*) FROM AdventureWorks.Person.Person
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
SELECT @Result_MiddleName = MiddleName FROM AdventureWorks.Person.Person WHERE LastName = 'Abbas'
END
go


